services:
  - type: web
    name: chittortech-whatsapp-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --legacy-peer-deps && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: USE_MONGODB
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: SERVER_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
